export const songs = [
    {
        id: 1,
        title: "Authentic Italian Pizza",
        duration: 53,
        audioUrl: "songs/AuthenticItalianPizza.ogg",
        imageUrl: "images/album-covers/AuthenticItalianPizza.webp",
        isLoop: true,
    },
    {
        id: 2,
        title: "DK Jungle Think",
        duration: 142,
        audioUrl: "songs/DKJungleThink.ogg",
        imageUrl: "images/album-covers/OutOfBreath.gif",
        isLoop: true,
    },
    {
        id: 3,
        title: "Border Ducky",
        duration: 49,
        audioUrl: "songs/BorderDucky.ogg",
        imageUrl: "images/album-covers/Girl.gif",
        isLoop: true,
    },
    {
        id: 4,
        title: "B-Side",
        duration: 64,
        audioUrl: "songs/BSide.ogg",
        imageUrl: "images/album-covers/GodotPaper.webp",
        isLoop: true,
    },
    {
        id: 5,
        title: "Pit Stop",
        duration: 67,
        audioUrl: "songs/PitStop.ogg",
        imageUrl: "images/album-covers/EvilBean.webp",
        isLoop: true,
    },
];
